In [1]:
import pandas as pd
metadata = pd.read_csv('movies_metadata.csv', low_memory=False)
metadata.head(3)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0

In [2]:
C = metadata['vote_average'].mean()
print(C)

5.618207215134185

In [3]:
m = metadata['vote_count'].quantile(0.85)
print(m)

82.0

In [6]:
q_movies = metadata.copy().loc[metadata['vote_count'] >=m]
q_movies.shape

(6832, 24)

In [7]:
metadata.shape

(45466, 24)

In [13]:
def weighted_rating(x,m=m,c=C):
  v = x['vote_count']
  R = x['vote_average']
  return  (v/(v+m) * R) + (m/(m+v) * C)

In [14]:
q_movies['score'] = q_movies.apply(weighted_rating,axis = 1)

In [15]:
q_movies = q_movies.sort_values('score',ascending = False)

In [17]:
q_movies[['title','vote_count','vote_average','score']].head(20)

                                 title  vote_count  vote_average     score
10309      Dilwale Dulhania Le Jayenge       661.0           9.1  8.715738
314           The Shawshank Redemption      8358.0           8.5  8.472002
834                      The Godfather      6024.0           8.5  8.461299
40251                       Your Name.      1030.0           8.5  8.287494
12481                  The Dark Knight     12269.0           8.3  8.282195
2843                        Fight Club      9678.0           8.3  8.277469
292                       Pulp Fiction      8670.0           8.3  8.274874
522                   Schindler's List      4436.0           8.3  8.251326
23673                         Whiplash      4376.0           8.3  8.250671
5481                     Spirited Away      3968.0           8.3  8.245702
2211                 Life Is Beautiful      3643.0           8.3  8.240965
1178            The Godfather: Part II      3418.0           8.3  8.237169
1152   One Flew Over the Cuckoo's Nest      3001.0           8.3  8.228671
1176                            Psycho      2405.0           8.3  8.211577
351                       Forrest Gump      8147.0           8.2  8.174273
1154           The Empire Strikes Back      5998.0           8.2  8.165180
18465                 The Intouchables      5410.0           8.2  8.161452
289             Leon: The Professional      4293.0           8.2  8.151610
3030                    The Green Mile      4166.0           8.2  8.150163
1170                        GoodFellas      3211.0           8.2  8.135710